using System.IO;

namespace McServerLauncher.Services;

/// <summary>
/// Generates the initial files of a new server: eula.txt, run.bat and a minimal
/// server.properties with the chosen port (Minecraft fills in the rest on the
/// first launch).
/// </summary>
public class ServerCreationService
{
    /// <summary>Accepts the Minecraft EULA by writing eula.txt.</summary>
    public void WriteEula(string folder)
    {
        File.WriteAllText(Path.Combine(folder, "eula.txt"),
            "# Generated by MC Server Launcher\r\neula=true\r\n");
    }

    /// <summary>
    /// Creates a run.bat equivalent to the one you would use manually (in case you want to launch it outside the app).
    /// </summary>
    public void WriteRunBat(string folder, int minGb, int maxGb, string jarFile, string javaPath = "java")
    {
        var java = javaPath.Contains(' ') ? $"\"{javaPath}\"" : javaPath;
        var content = $"@echo off\r\n{java} -Xms{minGb}G -Xmx{maxGb}G -jar \"{jarFile}\" nogui\r\npause\r\n";
        File.WriteAllText(Path.Combine(folder, "run.bat"), content);
    }

    /// <summary>
    /// Writes user_jvm_args.txt with the configured RAM. Modern Forge's own run.bat/run.sh read
    /// this file, so launching outside the app uses the same memory settings.
    /// </summary>
    public void WriteForgeUserJvmArgs(string folder, int minGb, int maxGb)
    {
        File.WriteAllText(Path.Combine(folder, "user_jvm_args.txt"),
            $"# Generated by MC Server Launcher\r\n-Xms{minGb}G\r\n-Xmx{maxGb}G\r\n");
    }

    /// <summary>
    /// Writes a minimal server.properties with the port and MOTD if it doesn't exist yet.
    /// Minecraft fills in the rest of the default properties on startup.
    /// </summary>
    /// <param name="folder">The new server's folder.</param>
    /// <param name="port">The port it listens on.</param>
    /// <param name="motd">The message the server list shows.</param>
    /// <param name="seed">
    /// The seed typed when creating it, or null or blank for a random one. Written as
    /// <c>level-seed</c>, which the server reads once, when it generates the world.
    /// </param>
    public void WriteInitialProperties(string folder, int port, string motd, string? seed = null)
    {
        var path = Path.Combine(folder, "server.properties");
        var hasSeed = !string.IsNullOrWhiteSpace(seed);

        if (File.Exists(path))
        {
            // A folder that already had a server keeps its file. The seed is still worth writing
            // when there is no world yet to have been generated with another one.
            if (hasSeed && !WorldExists(folder))
                new ServerPropertiesService().Update(path, new Dictionary<string, string>
                {
                    ["level-seed"] = WorldSeed.EscapeForProperties(seed!)
                });
            return;
        }

        // The MOTD derives from the user-typed server name: sanitize it so a pasted value with
        // line breaks can't inject extra keys into the file (see ServerPropertiesService).
        var safeMotd = ServerPropertiesService.SanitizeValue(motd);
        var content = $"#Minecraft server properties\r\nserver-port={port}\r\nmotd={safeMotd}\r\n";
        if (hasSeed) content += $"level-seed={WorldSeed.EscapeForProperties(seed!)}\r\n";
        File.WriteAllText(path, content);
    }

    /// <summary>Whether the folder already holds a generated world, which a seed can no longer change.</summary>
    public static bool WorldExists(string folder)
    {
        var props = new ServerPropertiesService().Read(Path.Combine(folder, "server.properties"));
        var level = props.TryGetValue("level-name", out var n) && n.Length > 0 ? n : "world";
        return File.Exists(Path.Combine(folder, level, "level.dat"));
    }
}
