using System.IO;

namespace McServerLauncher.Services;

/// <summary>
/// Generates the initial files of a new server: eula.txt, run.bat and a minimal
/// server.properties with the chosen port (Minecraft fills in the rest on the
/// first launch).
/// </summary>
public class ServerCreationService
{
    /// <summary>Accepts the Minecraft EULA by writing eula.txt.</summary>
    public void WriteEula(string folder)
    {
        File.WriteAllText(Path.Combine(folder, "eula.txt"),
            "# Generated by MC Server Launcher\r\neula=true\r\n");
    }

    /// <summary>
    /// Creates a run.bat equivalent to the one you would use manually (in case you want to launch it outside the app).
    /// </summary>
    public void WriteRunBat(string folder, int minGb, int maxGb, string jarFile, string javaPath = "java")
    {
        var java = javaPath.Contains(' ') ? $"\"{javaPath}\"" : javaPath;
        var content = $"@echo off\r\n{java} -Xms{minGb}G -Xmx{maxGb}G -jar \"{jarFile}\" nogui\r\npause\r\n";
        File.WriteAllText(Path.Combine(folder, "run.bat"), content);
    }

    /// <summary>
    /// Writes user_jvm_args.txt with the configured RAM. Modern Forge's own run.bat/run.sh read
    /// this file, so launching outside the app uses the same memory settings.
    /// </summary>
    public void WriteForgeUserJvmArgs(string folder, int minGb, int maxGb)
    {
        File.WriteAllText(Path.Combine(folder, "user_jvm_args.txt"),
            $"# Generated by MC Server Launcher\r\n-Xms{minGb}G\r\n-Xmx{maxGb}G\r\n");
    }

    /// <summary>
    /// Writes a minimal server.properties with the port and MOTD if it doesn't exist yet.
    /// Minecraft fills in the rest of the default properties on startup.
    /// </summary>
    public void WriteInitialProperties(string folder, int port, string motd)
    {
        var path = Path.Combine(folder, "server.properties");
        if (File.Exists(path))
            return;

        var content = $"#Minecraft server properties\r\nserver-port={port}\r\nmotd={motd}\r\n";
        File.WriteAllText(path, content);
    }
}
