#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Builds McServerLauncher/Resources/store-summaries.json from store_summaries_data.py.

Why a generator instead of hand-writing the JSON: the app matches a project by its
Modrinth id first (ids never change, slugs can be renamed), and typing 100+ ids by
hand is a guaranteed source of silent mistakes.  This asks Modrinth for the id of
every slug, and drops — loudly — any entry whose project no longer exists.

Usage:
    python tools/generate-store-summaries.py [--check]

    --check  don't write anything; fail if the committed JSON is out of date.

Requires only the standard library.
"""

import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from store_summaries_data import SUMMARIES  # noqa: E402

API = "https://api.modrinth.com/v2"
UA = {"User-Agent": "JuanP-G/MC-ServerLauncher"}
LANGS = ("es", "en", "de", "fr", "pt")

OUTPUT = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..",
    "McServerLauncher", "Resources", "store-summaries.json")


def fetch_projects(slugs):
    """Resolves slugs to Modrinth projects, 100 at a time (the API's bulk endpoint)."""
    found = {}
    for start in range(0, len(slugs), 100):
        batch = slugs[start:start + 100]
        url = f"{API}/projects?ids=" + urllib.parse.quote(json.dumps(batch))
        try:
            with urllib.request.urlopen(urllib.request.Request(url, headers=UA)) as resp:
                for project in json.load(resp):
                    found[project["slug"]] = project
        except urllib.error.HTTPError as err:
            print(f"  ! batch {start // 100}: HTTP {err.code}", file=sys.stderr)
        time.sleep(0.2)  # stay well inside Modrinth's rate limit
    return found


def validate(slug, texts):
    """Every entry must carry all five languages and no empty text."""
    problems = []
    for lang in LANGS:
        value = texts.get(lang)
        if not value or not value.strip():
            problems.append(f"{slug}: missing '{lang}'")
        elif len(value) > 400:
            problems.append(f"{slug}: '{lang}' is {len(value)} chars (max 400)")
    for extra in set(texts) - set(LANGS):
        problems.append(f"{slug}: unexpected language '{extra}'")
    return problems


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="verify the committed file is up to date instead of writing it")
    args = parser.parse_args()

    slugs = sorted(SUMMARIES)
    print(f"{len(slugs)} entries; asking Modrinth for their ids...")

    problems = []
    for slug in slugs:
        problems += validate(slug, SUMMARIES[slug])

    projects = fetch_projects(slugs)
    missing = [s for s in slugs if s not in projects]
    for slug in missing:
        problems.append(f"{slug}: no such project on Modrinth (renamed or removed)")

    if problems:
        print("\nProblems found:", file=sys.stderr)
        for problem in problems:
            print("  -", problem, file=sys.stderr)
        if missing and len(missing) == len(problems):
            print("\nDropping the missing entries and continuing.", file=sys.stderr)
        else:
            return 1

    entries = {}
    for slug in slugs:
        project = projects.get(slug)
        if project is None:
            continue
        entries[project["id"]] = dict(
            slug=slug,
            title=project.get("title", ""),
            **{lang: SUMMARIES[slug][lang] for lang in LANGS})

    document = {
        "$comment": (
            "Generated by tools/generate-store-summaries.py — edit "
            "tools/store_summaries_data.py and re-run it, not this file. "
            "Keyed by Modrinth project id; 'slug' is a fallback match and a "
            "readability aid."),
        "version": 1,
        "summaries": entries,
    }

    rendered = json.dumps(document, ensure_ascii=False, indent=1, sort_keys=False) + "\n"

    if args.check:
        try:
            with open(OUTPUT, encoding="utf-8") as handle:
                current = handle.read()
        except FileNotFoundError:
            current = None
        if current != rendered:
            print("store-summaries.json is out of date; re-run without --check.", file=sys.stderr)
            return 1
        print("store-summaries.json is up to date.")
        return 0

    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(rendered)
    print(f"Wrote {len(entries)} summaries to {os.path.normpath(OUTPUT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
